### ISSUE TITLE
关于训练dsb2018

### ISSUE THREAD

**Issue by riverfjs** [Andy-zhujunwen/UNET-ZOO#13]
为什么iou一直都很小，甚至都是0，已解决，colab和google drive的交互bug，换到服务器就没问题了

**Comment by ASguoyue** [comment]
> 为什么iou一直都很小，请问一下，那个你成功运行了吗我的报错了《
    "aforementioned parameters.".format(n_samples, test_size, train_size)
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by riverfjs** [comment]
> > 为什么iou一直都很小，请问一下，那个你成功运行了吗我的报错了《
> 
>     "aforementioned parameters.".format(n_samples, test_size, train_size)
> 
> ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

你这很明显是数据集路径不对...
